<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'DEFAULT_LABEL' => "Bu yerga bosing va rasmni tanlang yoki rasmni bu yerga suring",
    'CROP_PHOTO' => 'Rasmni qirqish',
    'DELETE_PHOTO' => 'Rasmni o\'chirish',
    'ERROR_CAN_NOT_UPLOAD_FILE' => 'Ushbu faylni yuklab bo\'lmaydi',
    'MISSING_ATTRIBUTE' => 'Attibute "{attribute}" must be specified',
    'ONLY_POST_REQUEST' => 'Allowed only POST-request',
    'UPLOAD_ANOTHER_PHOTO' => "Boshqa rasmni yuklash",
    'TOO_BIG_ERROR' => 'Exceeded the allowable size of the file ({size} Mb)',
    'EXTENSION_ERROR' => 'Enable only the following file formats: {formats}'
];
